---
- hosts: webservers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - ansible_role_extra_repositories # Enable EPEL and Remi's repositories
    - ansible_role_apache2
    - ansible_role_selinux # disable SELinux
    - ansible_role_php72